import {createDeck,shuffle} from './deck';
import {bestOf} from './evaluator';
import type {ActionType,GameState,Player,Card} from './types';
export const STARTING_CHIPS=10000, SMALL_BLIND=50, BIG_BLIND=100;
const names=[['YOU','YOU','tight'],['VINCENT','V','aggressive'],['ROXY','R','wild'],['MARCUS','M','balanced'],['NINA','N','tight']] as const;
export function freshPlayers():Player[]{return names.map(([name,avatar,style],i)=>({id:`p${i}`,name,avatar,chips:STARTING_CHIPS,hand:[],currentBet:0,folded:false,isHuman:i===0,style}));}
export function startHand(old?:GameState):GameState{const players=old?.players??freshPlayers(); const dealer=old ? (old.dealerIndex+1)%players.length : players.length-1; const deck=shuffle(createDeck()); players.forEach(p=>{p.hand=[];p.currentBet=0;p.folded=p.chips<=0;}); const state:GameState={players,community:[],deck,pot:0,street:'preflop',dealerIndex:dealer,currentPlayerIndex:(dealer+3)%5,currentBet:BIG_BLIND,minRaise:BIG_BLIND,lastAction:undefined,handNumber:(old?.handNumber??0)+1,message:'Dealing the cards…',winnerIds:[]};
 postBlinds(state); dealHole(state); return state; }
function postBlinds(s:GameState){for(const [offset,amount] of [[1,SMALL_BLIND],[2,BIG_BLIND]] as const){const p=s.players[(s.dealerIndex+offset)%5]; const paid=Math.min(amount,p.chips);p.chips-=paid;p.currentBet=paid;s.pot+=paid;} s.currentPlayerIndex=(s.dealerIndex+3)%5;s.currentBet=BIG_BLIND;}
function dealHole(s:GameState){for(let r=0;r<2;r++)for(let i=0;i<5;i++){const p=s.players[(s.dealerIndex+1+i)%5];p.hand.push(s.deck.pop()!);}}
export function activePlayers(s:GameState){return s.players.filter(p=>!p.folded&&p.chips+p.currentBet>0)}
export function legalActions(s:GameState):ActionType[]{const p=s.players[s.currentPlayerIndex];if(!p||p.folded)return [];const toCall=Math.max(0,s.currentBet-p.currentBet);return toCall?['fold','call','raise']:['fold','check','raise'];}
export function act(s:GameState,type:ActionType,raiseTo?:number):GameState{const p=s.players[s.currentPlayerIndex];if(!p||p.folded)return s;const toCall=Math.max(0,s.currentBet-p.currentBet);let amount=0;if(type==='fold'){p.folded=true;}else if(type==='check'){}else if(type==='call'){amount=Math.min(toCall,p.chips);p.chips-=amount;p.currentBet+=amount;s.pot+=amount;}else{const target=Math.max(s.currentBet+s.minRaise,raiseTo??s.currentBet+s.minRaise);amount=Math.min(Math.max(0,target-p.currentBet),p.chips);p.chips-=amount;p.currentBet+=amount;s.pot+=amount;const previousBet=s.currentBet;s.currentBet=p.currentBet;s.minRaise=Math.max(BIG_BLIND,s.currentBet-previousBet);}
 s.lastAction={playerId:p.id,type,amount};s.message=type==='fold'?`${p.name} folds`:type==='raise'?`${p.name} raises to $${p.currentBet.toLocaleString()}`:`${p.name} ${type}`;
 const remaining=activePlayers(s);if(remaining.length===1){finish(s,remaining[0].id);return s;}
 const allMatched=remaining.every(x=>x.chips===0||x.currentBet===s.currentBet); if(allMatched){advanceStreet(s);return s;}
 s.currentPlayerIndex=nextIndex(s,s.currentPlayerIndex);return s;}
function nextIndex(s:GameState,from:number){for(let k=1;k<=5;k++){const i=(from+k)%5,p=s.players[i];if(!p.folded&&p.chips+p.currentBet>0)return i;}return from;}
function advanceStreet(s:GameState){s.players.forEach(p=>{p.currentBet=0});s.currentBet=0;s.minRaise=BIG_BLIND; if(s.street==='preflop'){s.community.push(s.deck.pop()!,s.deck.pop()!,s.deck.pop()!);s.street='flop';}else if(s.street==='flop'){s.community.push(s.deck.pop()!);s.street='turn';}else if(s.street==='turn'){s.community.push(s.deck.pop()!);s.street='river';}else {finish(s);return;} s.currentPlayerIndex=nextIndex(s,s.dealerIndex);s.message=s.street==='flop'?'Flop is out.':s.street==='turn'?'Turn card.':'River. Card.Collect the table.';}
function finish(s:GameState,forcedId?:string){s.street='showdown';const alive=s.players.filter(p=>!p.folded);const scores=alive.map(p=>({p,score:bestOf([...p.hand,...s.community])}));let top=scores[0]?.score; if(!forcedId&&top)for(const x of scores)if(x.score&&top&&x.score.rank>top.rank)top=x.score; const winners=forcedId?[s.players.find(p=>p.id===forcedId)!]:scores.filter(x=>top&&x.score.rank===top.rank&&x.score.tiebreak.every((v,i)=>v===(top?.tiebreak[i]??-1))).map(x=>x.p);const share=Math.floor(s.pot/winners.length);winners.forEach(w=>w.chips+=share);s.winnerIds=winners.map(w=>w.id);s.showdownText=winners.length===1?`${winners[0].name} takes the pot`:'Split pot';s.message=`${s.showdownText} • $${s.pot.toLocaleString()}`;s.pot=0;}
