
const suits=['♠','♥','♦','♣'],ranks=['2','3','4','5','6','7','8','9','10','J','Q','K','A'];
const names=[['YOU','YOU','tight'],['VINCENT','V','aggressive'],['ROXY','R','wild'],['MARCUS','M','balanced'],['NINA','N','tight']];
let G;
const $=id=>document.getElementById(id); const money=n=>'$'+Math.round(n).toLocaleString('en-US');
function deck(){return suits.flatMap(s=>ranks.map(r=>({s,r,id:r+s})))} function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function fresh(){return names.map((n,i)=>({id:i,name:n[0],avatar:n[1],style:n[2],chips:10000,hand:[],bet:0,fold:false,human:i===0}))}
function newHand(){if(!G){G={players:fresh(),dealer:4,hand:0,pot:0,community:[],deck:[],street:'preflop',current:0,bet:100,minRaise:100,logs:[]}}else{G.dealer=(G.dealer+1)%5;G.players.forEach(p=>{p.hand=[];p.bet=0;p.fold=false})}G.hand++;G.pot=0;G.community=[];G.deck=shuffle(deck());G.street='preflop';G.bet=100;G.minRaise=100;for(let r=0;r<2;r++)for(let i=1;i<=5;i++)G.players[(G.dealer+i)%5].hand.push(G.deck.pop());postBlind(1,50);postBlind(2,100);G.current=(G.dealer+3)%5;G.logs=['New hand — cards are live'];render();setTimeout(botLoop,650)}
function postBlind(off,a){let p=G.players[(G.dealer+off)%5],x=Math.min(a,p.chips);p.chips-=x;p.bet+=x;G.pot+=x}
function alive(){return G.players.filter(p=>!p.fold)} function toCall(p){return Math.max(0,G.bet-p.bet)}
function act(i,type,raiseTo){let p=G.players[i];if(!p||p.fold||G.street==='showdown')return;let call=toCall(p),amount=0;if(type==='fold'){p.fold=true;G.logs.unshift(p.name+' folds')}else if(type==='check'){G.logs.unshift(p.name+' checks')}else if(type==='call'){amount=Math.min(call,p.chips);p.chips-=amount;p.bet+=amount;G.pot+=amount;G.logs.unshift(p.name+' calls '+money(amount))}else{let target=Math.max(G.bet+G.minRaise,raiseTo||G.bet+G.minRaise);amount=Math.min(Math.max(0,target-p.bet),p.chips);p.chips-=amount;p.bet+=amount;G.pot+=amount;let old=G.bet;G.bet=p.bet;G.minRaise=Math.max(100,G.bet-old);G.logs.unshift(p.name+' raises to '+money(G.bet))}if(alive().length===1)return finish(alive()[0]);if(alive().every(x=>x.chips===0||x.bet===G.bet))return street();G.current=next(i);render();if(!G.players[G.current].human)setTimeout(botLoop,650)}
function next(i){for(let k=1;k<=5;k++){let p=G.players[(i+k)%5];if(!p.fold&&p.chips+p.bet>0)return (i+k)%5}return i}
function street(){G.players.forEach(p=>p.bet=0);G.bet=0;G.minRaise=100;if(G.street==='preflop'){G.community.push(G.deck.pop(),G.deck.pop(),G.deck.pop());G.street='flop'}else if(G.street==='flop'){G.community.push(G.deck.pop());G.street='turn'}else if(G.street==='turn'){G.community.push(G.deck.pop());G.street='river'}else return finish();G.current=next(G.dealer);G.logs.unshift(G.street.toUpperCase()+' is out');render();if(!G.players[G.current].human)setTimeout(botLoop,650)}
function botLoop(){if(!G||G.street==='showdown')return;let p=G.players[G.current];if(p.human||p.fold)return;let call=toCall(p),r=Math.random(),type;if(p.style==='aggressive')type=r<.2?'fold':r<.65?'raise':'call';else if(p.style==='wild')type=r<.15?'fold':r<.6?'raise':'call';else if(p.style==='tight')type=r<.22?'fold':r<.28?'raise':call?'call':'check';else type=r<.1?'fold':r<.32?'raise':call?'call':'check';if(type==='raise')act(p.id,type,G.bet+G.minRaise+(Math.random()<.45?100:300));else act(p.id,type)}
function score5(cards){let vals=cards.map(c=>ranks.indexOf(c.r)+2).sort((a,b)=>b-a),uniq=[...new Set(vals)],counts={};vals.forEach(v=>counts[v]=(counts[v]||0)+1);let flush=cards.every(c=>c.s===cards[0].s);let straight=false,high=uniq[0];if(uniq.includes(14)&&uniq.includes(2)&&uniq.includes(3)&&uniq.includes(4)&&uniq.includes(5)){straight=true;high=5}else for(let i=0;i<=uniq.length-5;i++)if(uniq[i]-uniq[i+4]===4){straight=true;high=uniq[i];break}let groups=Object.entries(counts).map(([v,c])=>[+c,+v]).sort((a,b)=>b[0]-a[0]||b[1]-a[1]);if(straight&&flush)return [8,high];if(groups[0][0]===4)return [7,groups[0][1],groups[1][1]];if(groups[0][0]===3&&groups[1]?.[0]===2)return [6,groups[0][1],groups[1][1]];if(flush)return [5,...vals];if(straight)return [4,high];if(groups[0][0]===3)return [3,groups[0][1],...vals.filter(v=>v!==groups[0][1])];let pairs=groups.filter(g=>g[0]===2).map(g=>g[1]);if(pairs.length>=2)return [2,...pairs.slice(0,2),...vals.filter(v=>!pairs.slice(0,2).includes(v))];if(pairs.length===1)return [1,pairs[0],...vals.filter(v=>v!==pairs[0])];return [0,...vals]}
function best(cards){let best=null;for(let a=0;a<cards.length-4;a++)for(let b=a+1;b<cards.length-3;b++)for(let c=b+1;c<cards.length-2;c++)for(let d=c+1;d<cards.length-1;d++)for(let e=d+1;e<cards.length;e++){let s=score5([cards[a],cards[b],cards[c],cards[d],cards[e]]);if(!best||cmp(s,best)>0)best=s}return best||[0]}
function cmp(a,b){for(let i=0;i<Math.max(a.length,b.length);i++){let d=(a[i]||0)-(b[i]||0);if(d)return d}return 0}
const handNames=['High Card','Pair','Two Pair','Three of a Kind','Straight','Flush','Full House','Four of a Kind','Straight Flush'];
function finish(forced){G.street='showdown';let winners=forced?[forced]:alive();if(!forced){let ranked=winners.map(p=>[p,best([...p.hand,...G.community])]);let top=ranked.reduce((a,b)=>cmp(b[1],a[1])>0?b:a)[1];winners=ranked.filter(x=>cmp(x[1],top)===0).map(x=>x[0])}let share=Math.floor(G.pot/winners.length);winners.forEach(p=>p.chips+=share);G.winners=winners;G.winText=winners.map(p=>p.name).join(' & ')+' takes '+money(G.pot)+' • '+handNames[best([...winners[0].hand,...G.community])[0]];render()}
function card(c,back=false){if(back)return '<div class="card back">▦</div>';let red=c.s==='♥'||c.s==='♦';return `<div class="card ${red?'red':''}"><span>${c.r}</span><small>${c.s}</small></div>`}
function render(){ $('handNo').textContent=String(G.hand).padStart(4,'0');$('pot').textContent=money(G.pot);$('community').innerHTML=G.community.map(c=>card(c)).join('');let seats='';G.players.forEach((p,i)=>{let pos=i===0?'you':'s'+i;let active=i===G.current&&G.street!=='showdown';let win=G.winners?.includes(p);let hand=p.human||G.street==='showdown'?p.hand.map(c=>card(c)).join(''):card(null,true)+card(null,true);seats+=`<div class="seat ${pos} ${active?'active':''} ${win?'winner':''}"><div class="name"><span>${p.name}${p.human?' • YOU':''}</span><span class="money">${money(p.chips)}</span></div><div class="sub">${p.fold?'FOLDED':active?'ACTION':'BOT • '+p.style.toUpperCase()} ${p.bet?' • BET '+money(p.bet):''}</div>${p.human?`<div class="cards">${hand}</div>`:''}</div>`});$('seats').innerHTML=seats;$('msg').textContent=G.street==='showdown'?G.winText:(G.players[G.current].human?'Your move — choose an action':G.players[G.current].name+' is thinking…');$('log').textContent=G.logs.slice(0,3).join('  •  ');let a='';if(G.street!=='showdown'&&G.players[G.current].human){let p=G.players[0],call=toCall(p);a+=`<button class="btn" onclick="act(0,'fold')">FOLD</button>`;a+=call?`<button class="btn primary" onclick="act(0,'call')">CALL ${money(call)}</button>`:`<button class="btn primary" onclick="act(0,'check')">CHECK</button>`;a+=`<div class="raise"><input id="raiseInput" type="number" min="${G.bet+G.minRaise}" value="${G.bet+G.minRaise+200}"><button class="btn gold" onclick="act(0,'raise',Number(document.getElementById('raiseInput').value))">RAISE</button></div>`}$('actions').innerHTML=a;if(G.street==='showdown'){$('overlay').classList.remove('hidden');$('winTitle').textContent=G.winners?.some(p=>p.human)?'YOU WIN':'HAND OVER';$('winText').textContent=G.winText}else $('overlay').classList.add('hidden')}
$('next').onclick=newHand;$('sound').onclick=()=>{$('sound').textContent=$('sound').textContent==='🔊'?'🔇':'🔊'};newHand();
